//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://www.thatindigogirl.com/samples/2006/06", ConfigurationName="PhotoUploadContract")]
public interface PhotoUploadContract
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.thatindigogirl.com/samples/2006/06/PhotoUploadContract/UploadPhoto", ReplyAction="http://www.thatindigogirl.com/samples/2006/06/PhotoUploadContract/UploadPhotoResp" +
        "onse")]
    void UploadPhoto(ContentTypes.PhotoLink fileInfo, byte[] fileData);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface PhotoUploadContractChannel : PhotoUploadContract, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class PhotoUploadContractClient : System.ServiceModel.ClientBase<PhotoUploadContract>, PhotoUploadContract
{
    
    public PhotoUploadContractClient()
    {
    }
    
    public PhotoUploadContractClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public PhotoUploadContractClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public PhotoUploadContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public PhotoUploadContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public void UploadPhoto(ContentTypes.PhotoLink fileInfo, byte[] fileData)
    {
        base.Channel.UploadPhoto(fileInfo, fileData);
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://www.thatindigogirl.com/samples/2006/06", ConfigurationName="PhotoManagerContract")]
public interface PhotoManagerContract
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.thatindigogirl.com/samples/2006/06/PhotoManagerContract/GetPhotos", ReplyAction="http://www.thatindigogirl.com/samples/2006/06/PhotoManagerContract/GetPhotosRespo" +
        "nse")]
    System.Collections.Generic.List<ContentTypes.PhotoLink> GetPhotos();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.thatindigogirl.com/samples/2006/06/PhotoManagerContract/GetPhoto", ReplyAction="http://www.thatindigogirl.com/samples/2006/06/PhotoManagerContract/GetPhotoRespon" +
        "se")]
    ContentTypes.PhotoLink GetPhoto(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.thatindigogirl.com/samples/2006/06/PhotoManagerContract/GetCategories", ReplyAction="http://www.thatindigogirl.com/samples/2006/06/PhotoManagerContract/GetCategoriesR" +
        "esponse")]
    System.Collections.Generic.List<string> GetCategories();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface PhotoManagerContractChannel : PhotoManagerContract, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class PhotoManagerContractClient : System.ServiceModel.ClientBase<PhotoManagerContract>, PhotoManagerContract
{
    
    public PhotoManagerContractClient()
    {
    }
    
    public PhotoManagerContractClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public PhotoManagerContractClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public PhotoManagerContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public PhotoManagerContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public System.Collections.Generic.List<ContentTypes.PhotoLink> GetPhotos()
    {
        return base.Channel.GetPhotos();
    }
    
    public ContentTypes.PhotoLink GetPhoto(int id)
    {
        return base.Channel.GetPhoto(id);
    }
    
    public System.Collections.Generic.List<string> GetCategories()
    {
        return base.Channel.GetCategories();
    }
}
