//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5477
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://www.cacotopia.com/sample/2014/07", ConfigurationName="IHelloIndigoService")]
public interface IHelloIndigoService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.cacotopia.com/sample/2014/07/IHelloIndigoService/HelloIndigo", ReplyAction="http://www.cacotopia.com/sample/2014/07/IHelloIndigoService/HelloIndigoResponse")]
    string HelloIndigo();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IHelloIndigoServiceChannel : IHelloIndigoService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class HelloIndigoServiceClient : System.ServiceModel.ClientBase<IHelloIndigoService>, IHelloIndigoService
{
    
    public HelloIndigoServiceClient()
    {
    }
    
    public HelloIndigoServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public HelloIndigoServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public HelloIndigoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public HelloIndigoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string HelloIndigo()
    {
        return base.Channel.HelloIndigo();
    }
}
