//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5477
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GigEntry.localhost
{
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LinkItem", Namespace="http://schemas.thatindigogirl.com/samples/2006/06")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GigEntry.localhost.MP3Link))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GigEntry.localhost.GigInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GigEntry.localhost.PhotoLink))]
    public partial class LinkItem : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        private string TitleField;
        
        private string DescriptionField;
        
        private System.DateTime DateStartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateEndField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime DateStart
        {
            get
            {
                return this.DateStartField;
            }
            set
            {
                this.DateStartField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.DateTime DateEnd
        {
            get
            {
                return this.DateEndField;
            }
            set
            {
                this.DateEndField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string Url
        {
            get
            {
                return this.UrlField;
            }
            set
            {
                this.UrlField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MP3Link", Namespace="http://schemas.thatindigogirl.com/samples/2006/06")]
    [System.SerializableAttribute()]
    public partial class MP3Link : GigEntry.localhost.LinkItem
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GigInfo", Namespace="http://schemas.thatindigogirl.com/samples/2006/06")]
    [System.SerializableAttribute()]
    public partial class GigInfo : GigEntry.localhost.LinkItem
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PhotoLink", Namespace="http://schemas.thatindigogirl.com/samples/2006/06")]
    [System.SerializableAttribute()]
    public partial class PhotoLink : GigEntry.localhost.LinkItem
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.thatindigogirl.com/samples/2006/06", ConfigurationName="GigEntry.localhost.GigManagerServiceContract", SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface GigManagerServiceContract
    {
        
        // CODEGEN: 消息 SaveGigRequest 的包装名称(SaveGigRequest)以后生成的消息协定与默认值(SaveGig)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="http://www.thatindigogirl.com/samples/2006/06/GigManagerServiceContract/SaveGig", ReplyAction="http://www.thatindigogirl.com/samples/2006/06/GigManagerServiceContract/SaveGigRe" +
            "sponse")]
        GigEntry.localhost.SaveGigResponse SaveGig(GigEntry.localhost.SaveGigRequest request);
        
        // CODEGEN: 消息 GetGigRequest 的包装名称(GetGigRequest)以后生成的消息协定与默认值(GetGig)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="http://www.thatindigogirl.com/samples/2006/06/GigManagerServiceContract/GetGig", ReplyAction="http://www.thatindigogirl.com/samples/2006/06/GigManagerServiceContract/GetGigRes" +
            "ponse")]
        GigEntry.localhost.GetGigResponse GetGig(GigEntry.localhost.GetGigRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SaveGigRequest", WrapperNamespace="http://www.thatindigogirl.com/samples/2006/06", IsWrapped=true)]
    public partial class SaveGigRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.thatindigogirl.com/samples/2006/06", Order=0)]
        public GigEntry.localhost.LinkItem Item;
        
        public SaveGigRequest()
        {
        }
        
        public SaveGigRequest(GigEntry.localhost.LinkItem Item)
        {
            this.Item = Item;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SaveGigResponse", WrapperNamespace="http://www.thatindigogirl.com/samples/2006/06", IsWrapped=true)]
    public partial class SaveGigResponse
    {
        
        public SaveGigResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetGigRequest", WrapperNamespace="http://www.thatindigogirl.com/samples/2006/06", IsWrapped=true)]
    public partial class GetGigRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.thatindigogirl.com/samples/2006/06")]
        public string LicenseKey;
        
        public GetGigRequest()
        {
        }
        
        public GetGigRequest(string LicenseKey)
        {
            this.LicenseKey = LicenseKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetGigResponse", WrapperNamespace="http://www.thatindigogirl.com/samples/2006/06", IsWrapped=true)]
    public partial class GetGigResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.thatindigogirl.com/samples/2006/06", Order=0)]
        public GigEntry.localhost.LinkItem Item;
        
        public GetGigResponse()
        {
        }
        
        public GetGigResponse(GigEntry.localhost.LinkItem Item)
        {
            this.Item = Item;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface GigManagerServiceContractChannel : GigEntry.localhost.GigManagerServiceContract, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class GigManagerServiceContractClient : System.ServiceModel.ClientBase<GigEntry.localhost.GigManagerServiceContract>, GigEntry.localhost.GigManagerServiceContract
    {
        
        public GigManagerServiceContractClient()
        {
        }
        
        public GigManagerServiceContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public GigManagerServiceContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public GigManagerServiceContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public GigManagerServiceContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GigEntry.localhost.SaveGigResponse GigEntry.localhost.GigManagerServiceContract.SaveGig(GigEntry.localhost.SaveGigRequest request)
        {
            return base.Channel.SaveGig(request);
        }
        
        public void SaveGig(GigEntry.localhost.LinkItem Item)
        {
            GigEntry.localhost.SaveGigRequest inValue = new GigEntry.localhost.SaveGigRequest();
            inValue.Item = Item;
            GigEntry.localhost.SaveGigResponse retVal = ((GigEntry.localhost.GigManagerServiceContract)(this)).SaveGig(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GigEntry.localhost.GetGigResponse GigEntry.localhost.GigManagerServiceContract.GetGig(GigEntry.localhost.GetGigRequest request)
        {
            return base.Channel.GetGig(request);
        }
        
        public GigEntry.localhost.LinkItem GetGig(string LicenseKey)
        {
            GigEntry.localhost.GetGigRequest inValue = new GigEntry.localhost.GetGigRequest();
            inValue.LicenseKey = LicenseKey;
            GigEntry.localhost.GetGigResponse retVal = ((GigEntry.localhost.GigManagerServiceContract)(this)).GetGig(inValue);
            return retVal.Item;
        }
    }
}
