//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinClient.localhost
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.thatindigogirl.com/2006/06/Samples", ConfigurationName="WinClient.localhost.SecureServiceContract")]
    public interface SecureServiceContract
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.thatindigogirl.com/2006/06/Samples/SecureServiceContract/AdminOperatio" +
            "n", ReplyAction="http://www.thatindigogirl.com/2006/06/Samples/SecureServiceContract/AdminOperatio" +
            "nResponse")]
        string AdminOperation();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.thatindigogirl.com/2006/06/Samples/SecureServiceContract/UserOperation" +
            "", ReplyAction="http://www.thatindigogirl.com/2006/06/Samples/SecureServiceContract/UserOperation" +
            "Response")]
        string UserOperation();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.thatindigogirl.com/2006/06/Samples/SecureServiceContract/GuestOperatio" +
            "n", ReplyAction="http://www.thatindigogirl.com/2006/06/Samples/SecureServiceContract/GuestOperatio" +
            "nResponse")]
        string GuestOperation();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface SecureServiceContractChannel : WinClient.localhost.SecureServiceContract, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class SecureServiceContractClient : System.ServiceModel.ClientBase<WinClient.localhost.SecureServiceContract>, WinClient.localhost.SecureServiceContract
    {
        
        public SecureServiceContractClient()
        {
        }
        
        public SecureServiceContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public SecureServiceContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public SecureServiceContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public SecureServiceContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public string AdminOperation()
        {
            return base.Channel.AdminOperation();
        }
        
        public string UserOperation()
        {
            return base.Channel.UserOperation();
        }
        
        public string GuestOperation()
        {
            return base.Channel.GuestOperation();
        }
    }
}
