//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoUploadClient.localhost
{
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.thatindigogirl.com/samples/2006/06")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PhotoUploadClient.localhost.MP3Link))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PhotoUploadClient.localhost.GigInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PhotoUploadClient.localhost.PhotoLink))]
    public partial class LinkItem : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        private string TitleField;
        
        private string DescriptionField;
        
        private System.DateTime DateStartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateEndField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlField;
        
        private string CategoryField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime DateStart
        {
            get
            {
                return this.DateStartField;
            }
            set
            {
                this.DateStartField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.Nullable<System.DateTime> DateEnd
        {
            get
            {
                return this.DateEndField;
            }
            set
            {
                this.DateEndField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string Url
        {
            get
            {
                return this.UrlField;
            }
            set
            {
                this.UrlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public string Category
        {
            get
            {
                return this.CategoryField;
            }
            set
            {
                this.CategoryField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.thatindigogirl.com/samples/2006/06")]
    [System.SerializableAttribute()]
    public partial class MP3Link : PhotoUploadClient.localhost.LinkItem
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.thatindigogirl.com/samples/2006/06")]
    [System.SerializableAttribute()]
    public partial class GigInfo : PhotoUploadClient.localhost.LinkItem
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.thatindigogirl.com/samples/2006/06")]
    [System.SerializableAttribute()]
    public partial class PhotoLink : PhotoUploadClient.localhost.LinkItem
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.thatindigogirl.com/samples/2006/06", ConfigurationName="PhotoUploadClient.localhost.PhotoUploadContract")]
    public interface PhotoUploadContract
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.thatindigogirl.com/samples/2006/06/PhotoUploadContract/UploadPhoto", ReplyAction="http://www.thatindigogirl.com/samples/2006/06/PhotoUploadContract/UploadPhotoResp" +
            "onse")]
        void UploadPhoto(PhotoUploadClient.localhost.PhotoLink fileInfo, byte[] fileData);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface PhotoUploadContractChannel : PhotoUploadClient.localhost.PhotoUploadContract, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class PhotoUploadContractClient : System.ServiceModel.ClientBase<PhotoUploadClient.localhost.PhotoUploadContract>, PhotoUploadClient.localhost.PhotoUploadContract
    {
        
        public PhotoUploadContractClient()
        {
        }
        
        public PhotoUploadContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public PhotoUploadContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public PhotoUploadContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public PhotoUploadContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public void UploadPhoto(PhotoUploadClient.localhost.PhotoLink fileInfo, byte[] fileData)
        {
            base.Channel.UploadPhoto(fileInfo, fileData);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.thatindigogirl.com/samples/2006/06", ConfigurationName="PhotoUploadClient.localhost.PhotoManagerContract")]
    public interface PhotoManagerContract
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.thatindigogirl.com/samples/2006/06/PhotoManagerContract/GetPhotos", ReplyAction="http://www.thatindigogirl.com/samples/2006/06/PhotoManagerContract/GetPhotosRespo" +
            "nse")]
        System.ComponentModel.BindingList<PhotoUploadClient.localhost.PhotoLink> GetPhotos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.thatindigogirl.com/samples/2006/06/PhotoManagerContract/GetPhoto", ReplyAction="http://www.thatindigogirl.com/samples/2006/06/PhotoManagerContract/GetPhotoRespon" +
            "se")]
        PhotoUploadClient.localhost.PhotoLink GetPhoto(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.thatindigogirl.com/samples/2006/06/PhotoManagerContract/GetCategories", ReplyAction="http://www.thatindigogirl.com/samples/2006/06/PhotoManagerContract/GetCategoriesR" +
            "esponse")]
        System.ComponentModel.BindingList<string> GetCategories();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface PhotoManagerContractChannel : PhotoUploadClient.localhost.PhotoManagerContract, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class PhotoManagerContractClient : System.ServiceModel.ClientBase<PhotoUploadClient.localhost.PhotoManagerContract>, PhotoUploadClient.localhost.PhotoManagerContract
    {
        
        public PhotoManagerContractClient()
        {
        }
        
        public PhotoManagerContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public PhotoManagerContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public PhotoManagerContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public PhotoManagerContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.ComponentModel.BindingList<PhotoUploadClient.localhost.PhotoLink> GetPhotos()
        {
            return base.Channel.GetPhotos();
        }
        
        public PhotoUploadClient.localhost.PhotoLink GetPhoto(int id)
        {
            return base.Channel.GetPhoto(id);
        }
        
        public System.ComponentModel.BindingList<string> GetCategories()
        {
            return base.Channel.GetCategories();
        }
    }
}
