//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CountersClient.localhost
{
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.thatindigogirl.com/samples/2006/06")]
    [System.SerializableAttribute()]
    public partial class CounterInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CounterValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CounterValue
        {
            get
            {
                return this.CounterValueField;
            }
            set
            {
                this.CounterValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.thatindigogirl.com/samples/2006/06", ConfigurationName="CountersClient.localhost.ICountersService")]
    public interface ICountersService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.thatindigogirl.com/samples/2006/06/ICountersService/ResetCounters", ReplyAction="http://www.thatindigogirl.com/samples/2006/06/ICountersService/ResetCountersRespo" +
            "nse")]
        [System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Allowed)]
        void ResetCounters();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.thatindigogirl.com/samples/2006/06/ICountersService/SetCounter1", ReplyAction="http://www.thatindigogirl.com/samples/2006/06/ICountersService/SetCounter1Respons" +
            "e")]
        [System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Mandatory)]
        void SetCounter1(int counterValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.thatindigogirl.com/samples/2006/06/ICountersService/SetCounter2", ReplyAction="http://www.thatindigogirl.com/samples/2006/06/ICountersService/SetCounter2Respons" +
            "e")]
        [System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Mandatory)]
        void SetCounter2(int counterValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.thatindigogirl.com/samples/2006/06/ICountersService/GetCounters", ReplyAction="http://www.thatindigogirl.com/samples/2006/06/ICountersService/GetCountersRespons" +
            "e")]
        [System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.NotAllowed)]
        System.ComponentModel.BindingList<CountersClient.localhost.CounterInfo> GetCounters();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ICountersServiceChannel : CountersClient.localhost.ICountersService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class CountersServiceClient : System.ServiceModel.ClientBase<CountersClient.localhost.ICountersService>, CountersClient.localhost.ICountersService
    {
        
        public CountersServiceClient()
        {
        }
        
        public CountersServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public CountersServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public CountersServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public CountersServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public void ResetCounters()
        {
            base.Channel.ResetCounters();
        }
        
        public void SetCounter1(int counterValue)
        {
            base.Channel.SetCounter1(counterValue);
        }
        
        public void SetCounter2(int counterValue)
        {
            base.Channel.SetCounter2(counterValue);
        }
        
        public System.ComponentModel.BindingList<CountersClient.localhost.CounterInfo> GetCounters()
        {
            return base.Channel.GetCounters();
        }
    }
}
