//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinClient.localhost
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.thatindigogirl.com/samples/2006/06", ConfigurationName="WinClient.localhost.ICounterService")]
    public interface ICounterService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.thatindigogirl.com/samples/2006/06/ICounterService/IncrementCounter", ReplyAction="http://www.thatindigogirl.com/samples/2006/06/ICounterService/IncrementCounterRes" +
            "ponse")]
        int IncrementCounter();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.thatindigogirl.com/samples/2006/06/ICounterService/ThrowException", ReplyAction="http://www.thatindigogirl.com/samples/2006/06/ICounterService/ThrowExceptionRespo" +
            "nse")]
        void ThrowException();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.thatindigogirl.com/samples/2006/06/ICounterService/ThrowFault", ReplyAction="http://www.thatindigogirl.com/samples/2006/06/ICounterService/ThrowFaultResponse")]
        void ThrowFault();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ICounterServiceChannel : WinClient.localhost.ICounterService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class CounterServiceClient : System.ServiceModel.ClientBase<WinClient.localhost.ICounterService>, WinClient.localhost.ICounterService
    {
        
        public CounterServiceClient()
        {
        }
        
        public CounterServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public CounterServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public CounterServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public CounterServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public int IncrementCounter()
        {
            return base.Channel.IncrementCounter();
        }
        
        public void ThrowException()
        {
            base.Channel.ThrowException();
        }
        
        public void ThrowFault()
        {
            base.Channel.ThrowFault();
        }
    }
}
