//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaClient.localhost
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.thatindigogirl.com/samples/2006/06", ConfigurationName="MediaClient.localhost.MediaManagerContract")]
    public interface MediaManagerContract
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.thatindigogirl.com/samples/2006/06/MediaManagerContract/GetMediaList", ReplyAction="http://www.thatindigogirl.com/samples/2006/06/MediaManagerContract/GetMediaListRe" +
            "sponse")]
        System.ComponentModel.BindingList<string> GetMediaList();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface MediaManagerContractChannel : MediaClient.localhost.MediaManagerContract, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class MediaManagerContractClient : System.ServiceModel.ClientBase<MediaClient.localhost.MediaManagerContract>, MediaClient.localhost.MediaManagerContract
    {
        
        public MediaManagerContractClient()
        {
        }
        
        public MediaManagerContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public MediaManagerContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public MediaManagerContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public MediaManagerContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.ComponentModel.BindingList<string> GetMediaList()
        {
            return base.Channel.GetMediaList();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.thatindigogirl.com/samples/2006/06", ConfigurationName="MediaClient.localhost.MediaStreamingContract")]
    public interface MediaStreamingContract
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.thatindigogirl.com/samples/2006/06/MediaStreamingContract/GetMediaStre" +
            "am", ReplyAction="http://www.thatindigogirl.com/samples/2006/06/MediaStreamingContract/GetMediaStre" +
            "amResponse")]
        System.IO.Stream GetMediaStream(string media);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface MediaStreamingContractChannel : MediaClient.localhost.MediaStreamingContract, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class MediaStreamingContractClient : System.ServiceModel.ClientBase<MediaClient.localhost.MediaStreamingContract>, MediaClient.localhost.MediaStreamingContract
    {
        
        public MediaStreamingContractClient()
        {
        }
        
        public MediaStreamingContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public MediaStreamingContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public MediaStreamingContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public MediaStreamingContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.IO.Stream GetMediaStream(string media)
        {
            return base.Channel.GetMediaStream(media);
        }
    }
}
