//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://www.thatindigogirl.com/samples/2006/06", ConfigurationName="IMessagingService")]
public interface IMessagingService
{
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://www.thatindigogirl.com/samples/2006/06/IMessagingService/SendMessage1")]
    void SendMessage1(string message);
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, AsyncPattern=true, Action="http://www.thatindigogirl.com/samples/2006/06/IMessagingService/SendMessage1")]
    System.IAsyncResult BeginSendMessage1(string message, System.AsyncCallback callback, object asyncState);
    
    void EndSendMessage1(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://www.thatindigogirl.com/samples/2006/06/IMessagingService/SendMessage2")]
    void SendMessage2(string message);
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, AsyncPattern=true, Action="http://www.thatindigogirl.com/samples/2006/06/IMessagingService/SendMessage2")]
    System.IAsyncResult BeginSendMessage2(string message, System.AsyncCallback callback, object asyncState);
    
    void EndSendMessage2(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://www.thatindigogirl.com/samples/2006/06/IMessagingService/SendMessage3")]
    void SendMessage3(string message);
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, AsyncPattern=true, Action="http://www.thatindigogirl.com/samples/2006/06/IMessagingService/SendMessage3")]
    System.IAsyncResult BeginSendMessage3(string message, System.AsyncCallback callback, object asyncState);
    
    void EndSendMessage3(System.IAsyncResult result);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IMessagingServiceChannel : IMessagingService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class MessagingServiceClient : System.ServiceModel.ClientBase<IMessagingService>, IMessagingService
{
    
    public MessagingServiceClient()
    {
    }
    
    public MessagingServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public MessagingServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public MessagingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public MessagingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public void SendMessage1(string message)
    {
        base.Channel.SendMessage1(message);
    }
    
    public System.IAsyncResult BeginSendMessage1(string message, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginSendMessage1(message, callback, asyncState);
    }
    
    public void EndSendMessage1(System.IAsyncResult result)
    {
        base.Channel.EndSendMessage1(result);
    }
    
    public void SendMessage2(string message)
    {
        base.Channel.SendMessage2(message);
    }
    
    public System.IAsyncResult BeginSendMessage2(string message, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginSendMessage2(message, callback, asyncState);
    }
    
    public void EndSendMessage2(System.IAsyncResult result)
    {
        base.Channel.EndSendMessage2(result);
    }
    
    public void SendMessage3(string message)
    {
        base.Channel.SendMessage3(message);
    }
    
    public System.IAsyncResult BeginSendMessage3(string message, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginSendMessage3(message, callback, asyncState);
    }
    
    public void EndSendMessage3(System.IAsyncResult result)
    {
        base.Channel.EndSendMessage3(result);
    }
}
